Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "devops-hometasks.1"
        vb.memory = "512"
    end 
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8081, host: 8081
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y mc
        apt-get install -y apache2
        apt-get install -y php7.4
        apt-get install -y libapache2-mod-php7.4
        a2enmod php7.4

        mkdir -p /var/www/domain_1/html
        mkdir -p /var/www/domain_2/html

        cp /vagrant/ports.conf /etc/apache2/ports.conf

        cp /vagrant/domain_1/site-config/domain_1.conf /etc/apache2/sites-available/domain_1.conf
        cp /vagrant/domain_2/site-config/domain_2.conf /etc/apache2/sites-available/domain_2.conf

        cp -r /vagrant/domain_1/html /var/www/domain_1
        cp -r /vagrant/domain_2/html /var/www/domain_2

        a2ensite domain_1.conf
        a2ensite domain_2.conf

        echo "ServerName 127.0.0.1">> /etc/apache2/apache2.conf # disable error AH00558

        service apache2 restart
    SHELL

end