Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provider "virtualbox" do |vb|
        vb.cpus   = 2
        vb.memory = 4096
    end 

    config.vm.define "docker.vm" do |docker|
        docker.vm.network "private_network", ip: "192.168.35.20"
        docker.vm.hostname = "docker.vm"
        docker.vm.provider "virtualbox" do |vb|
            vb.name = docker.vm.hostname
        end  

        docker.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y mc docker.io nginx
        sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        sudo dpkg -i minikube_latest_amd64.deb
        sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        sudo minikube start --driver docker --force --static-ip 192.168.200.200
        echo "192.168.200.200 wcg-app-test.com" >> /etc/hosts
        sudo minikube addons enable ingress
        SHELL
    end 
end