Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provider "virtualbox" do |vb|
        vb.cpus   = 2
        vb.memory = 1536
    end 

    config.vm.define "jenkins.vm" do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.35.10"
        jenkins.vm.hostname = "jenkins.vm"
        jenkins.vm.provider "virtualbox" do |vb|
            vb.name = "jenkins.vm"
        end        

        jenkins.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.inventory_path = "inventory"
            ansible.compatibility_mode = "2.0"
        end    
    
    end 

end