Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos7"
    config.vm.synced_folder ".", "/vagrant" , type: "rsync"

    config.vm.provider "virtualbox" do |vb|
        vb.cpus   = 1
        vb.memory = 512
    end 

    config.vm.define "master.puppet", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.34.10"
        master.vm.provider "virtualbox" do |vb|
            #vb.cpus   = 2
            vb.memory = 1536
            vb.name = "master.puppet"
        end        

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.inventory_path = "inventory"
            ansible.compatibility_mode = "2.0"
        end          
    end

    config.vm.define "slave1.puppet" do |slave|
        slave.vm.network "private_network", ip: "192.168.34.11"
        slave.vm.provider "virtualbox" do |vb|
            vb.name = "slave1.puppet"
        end        

        slave.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.inventory_path = "inventory"
            ansible.compatibility_mode = "2.0"
        end          
    end    

    config.vm.define "slave2.puppet" do |slave|
        slave.vm.network "private_network", ip: "192.168.34.12"
        slave.vm.provider "virtualbox" do |vb|
            vb.name = "slave2.puppet"
        end  

        slave.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.inventory_path = "inventory"
            ansible.compatibility_mode = "2.0"
        end          
    end    

    config.vm.define "mineserver.puppet" do |slave|
        slave.vm.network "private_network", ip: "192.168.34.13"
        slave.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.name = "mineserver.puppet"
        end  

        slave.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.inventory_path = "inventory"
            ansible.compatibility_mode = "2.0"
        end          
    end    

end