Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "devops-hometasks.2"
        vb.memory = "1024"
    end 

    config.vm.define "static" do |static|
        static.vm.network "private_network", ip: "192.168.33.10"
        static.vm.provider "virtualbox" do |vb|
            vb.name = "devops-hometasks.2.1"
            vb.memory = "512"
        end        

        static.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "static.yaml"
            ansible.limit = 'all'
            ansible.inventory_path = "inventory"
            ansible.compatibility_mode = "2.0"
        end    
    
    end 

    config.vm.define "dynamic" do |dynamic|
        dynamic.vm.network "private_network", ip: "192.168.33.11"
        dynamic.vm.provider "virtualbox" do |vb|
            vb.name = "devops-hometasks.2.2"
            vb.memory = "512"
        end        

        dynamic.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "dynamic.yaml"
            ansible.limit = 'all'
            ansible.inventory_path = "inventory"
            ansible.compatibility_mode = "2.0"
        end    
    
    end 

    config.vm.define "nginx" do |nginx|
        nginx.vm.network "private_network", ip: "192.168.33.12"
        nginx.vm.provider "virtualbox" do |vb|
            vb.name = "devops-hometasks.2.3"
            vb.memory = "512"
        end        

        nginx.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "nginx.yaml"
            ansible.limit = 'all'
            ansible.inventory_path = "inventory"
            ansible.compatibility_mode = "2.0"
        end    
    
    end 

end