Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "devops-hometasks.2"
        vb.memory = "1024"
    end 

    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8081, host: 8081
    #config.vm.network "private_network", ip: "192.168.33.12"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "main.yaml"
        ansible.limit = 'all'
        ansible.inventory_path = "inventory"
        ansible.compatibility_mode = "2.0"
    end    

end