Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.define "home1" do |home1|
        home1.vm.network "private_network", ip: "192.168.33.10"
        home1.vm.provider "virtualbox" do |vb|
            vb.name = "devops-hometasks.1.1"
            vb.memory = "512"
        end        
        home1.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y mc
            apt-get install -y apache2

            mkdir -p /var/www/domain_1/html

            cp /vagrant/domain_1/site-config/domain_1.conf /etc/apache2/sites-available/domain_1.conf

            cp -r /vagrant/domain_1/html /var/www/domain_1

            a2dissite 000-default.conf
            a2ensite domain_1.conf

            echo "ServerName 127.0.0.1">> /etc/apache2/apache2.conf # disable error AH00558

            service apache2 restart
        SHELL

    end 

    config.vm.define "home2" do |home2|
        home2.vm.network "private_network", ip: "192.168.33.11"
        home2.vm.provider "virtualbox" do |vb|
            vb.name = "devops-hometasks.1.2"
            vb.memory = "512"
        end        
        home2.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y mc
        apt-get install -y apache2
        apt-get install -y php7.4
        apt-get install -y libapache2-mod-php7.4
        a2enmod php7.4

        mkdir -p /var/www/domain_2/html

        cp /vagrant/domain_2/site-config/domain_2.conf /etc/apache2/sites-available/domain_2.conf

        cp -r /vagrant/domain_2/html /var/www/domain_2

        a2dissite 000-default.conf
        a2ensite domain_2.conf

        echo "ServerName 127.0.0.1">> /etc/apache2/apache2.conf # disable error AH00558

        service apache2 restart
        SHELL
    end 

end