# Default values for wcg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  label: wcg-app
  port: 8888
  name: app

image:
  repository: ghcr.io/smirnovalexey/wcg
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  name: wcg-srv
  type: NodePort
  port: 8888

ingress:
  name: wcg-ingress
  host: 'wcg-app-test.com'
  path: /
  pathType: Prefix

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
