unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope:    GLOBAL
          id:       nexus_creds
          username: "{{ nexus_user }}"
          password: "{{ nexus_password }}"
      - usernamePassword:
          scope:    GLOBAL
          id:       staging
          username: "{{ staging_user }}"
          password: "{{ staging_password }}"
      - usernamePassword:
          scope:    GLOBAL
          id:       prod
          username: "{{ staging_user }}"
          password: "{{ staging_password }}"

tool:
  go:
    installations:
    - name: "go_lang"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.16"