name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build /07-docker -t wcg -f Dockerfile.multi
          

    # - name: upload artifact
    #   run: |
    #     curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASSWORD }} --upload-file artifacts/linux/word-cloud-generator \
    #       http://46.56.80.84:8091/repository/word-cloud-build/github/test/2.0/word-cloud-generator.gz

