name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build ./07-docker -t wcg -f ./07-docker/Dockerfile.multi
          
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: ./07-docker
        file: Dockerfile.multi
        push: true
        tags: wcg1
        labels: wcg
