name: CI

on: 
  push:
  workflow_dispatch:
  
env:
  REPOSITORY_NAME: ${{ github.repository_owner }}
  APP_NAME: wcg
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: github.sha
      run: echo ${{ github.sha }}
    - name: REPOSITORY_NAME
      run: echo ${REPOSITORY_NAME}
    - name: APP_NAME
      run: echo ${APP_NAME}
          
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACTION_TOKEN }}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: ./07-docker
        file: ./07-docker/Dockerfile.multi
        push: true
        tags: ghcr.io/${REPOSITORY_NAME}/${APP_NAME}:latest
        # , ghcr.io/$REPOSITORY_NAME/$APP_NAME:${{ github.sha }}
